-- Generated by Babelfish, then imported/exported with the wowace localization tool

local L = LibStub("AceLocale-3.0"):NewLocale("Bazooka", "enUS", true)

L["|cffeda55fDrag|r to move the frame"] = "|cffeda55fDrag|r to move the frame"
L["|cffeda55fLeft Click|r to lock/unlock frames"] = "|cffeda55fLeft Click|r to lock/unlock frames"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55fRight Click|r to open the configuration window"
L["Disable %s plugin?"] = "Disable %s plugin?"
L["Bar"] = "Bar"
L["Bar#%d"] = "Bar#%d"
L["left"] = "Left"
L["cleft"] = "Center-Left"
L["center"] = "Center"
L["cright"] = "Center-Right"
L["right"] = "Right"
L["top"] = "Top"
L["bottom"] = "Bottom"
L["none"] = "None"
